
// Recipe endpoints
POST http://localhost:4000/recipes/create
Content-Type: application/json

{
    "name": "hope this works",
    "serving": 2,
    "cookTime": "All day",
    "instruction": "Just order out instead",
    "ingredientId": []
}

###
GET http://localhost:4000/recipes/get

###
GET http://localhost:4000/recipes/get/5ee6cb54ea72e64914742efc

###
PATCH http://localhost:4000/recipes/update/5ee52915d1ef5e4b68173b6d
Content-Type: application/json

{
    "name": "updated",
    "serving": 2,
    "cookTime": "All day",
    "instruction": "Just order out instead"
}

###
DELETE http://localhost:4000/recipes/delete/5ee52915d1ef5e4b68173b6d


// Ingredient endpoints
###
POST http://localhost:4000/ingredients/create/5ee6cb54ea72e64914742efc
Content-Type: application/json

{
    "name": "omga21212",
    "amount": "2 pinches"
}

###
GET http://localhost:4000/ingredients/get

###
GET http://localhost:4000/ingredients/get/5ee6cbb4ea72e64914742efd

###
