
// Recipe endpoints
POST http://localhost:4000/recipes/create
Content-Type: application/json

{
    "name": "hope this works2",
    "serving": 2,
    "cookTime": "All day",
    "instruction": "Just order out instead"
}

###
GET http://localhost:4000/recipes/get

###
GET http://localhost:4000/recipes/get/5ee731b64a238e324cab2c96

###
PATCH http://localhost:4000/recipes/update/5ee731b64a238e324cab2c96
Content-Type: application/json

{
    "name": "updated",
    "serving": 2,
    "cookTime": "All day",
    "instruction": "Just order out instead"
}

###
DELETE http://localhost:4000/recipes/delete/5ee732c44a238e324cab2c97


// Ingredient endpoints
###
POST http://localhost:4000/ingredients/create/5ee731b64a238e324cab2c96
Content-Type: application/json

{
    "name": "omga234",
    "amount": "2 pinches"
}

###
GET http://localhost:4000/ingredients/get

###
GET http://localhost:4000/ingredients/get/5ee734d81cdb052834232923

###
PATCH http://localhost:4000/ingredients/update/5ee734d81cdb052834232923
Content-Type: application/json

{
    "name": "updated",
    "amount": "2 pinches"
}

###
DELETE http://localhost:4000/ingredients/delete/5ee734d81cdb052834232923